packages = [
    "numpy",
    "gmpy2",
    "ssl",
    "pandas",
    "matplotlib",
    "scipy",
    "lifelines",
    "setuptools",
    "rich"
]

# "https://e-nikolov.github.io/mpyc/py/mpyc-0.8.8-py3-none-any.whl"
# "http://localhost:5173/mpyc/py/mpyc-0.8.8-py3-none-any.whl"
# "/pyodide/mpyc-0.8.8-py3-none-any.whl"
# 
# packages = ["numpy", "gmpy2", "ssl", "aiortc"]
# xterm = true

# plugins = ["py-terminal.py"]
# plugins = ["py-term.js"]
# plugins = ["py-term.py"] 
# [[fetch]]
# from = "./py/"
# to_folder = "./"
# files = ["logging_setup.py"]

[[fetch]]
from = "./py/mpycweb"
to_folder = "./mpycweb"
files = [
    "__init__.py",
    "debug.py",
    "patches.py",
    "peerjs.py",
    "transport.py",
    "worker_init.py",
    "worker.py",
    "log.py",
    "stats.py"
]

[[fetch]]
from = "./py/mpyc/demos"
to_folder = "./"
files = [
    "data/lp/kb2.csv",
    "data/lp/LPExample_R20.csv",
    "data/lp/LPExample.csv",
    "data/lp/sc50b.csv",
    "data/lp/tb2x2.csv",
    "data/lp/uvlp.csv",
    "data/lp/wiki.csv",
    "data/lp/woody.csv",
    "data/surv/aml.csv",
    "data/surv/btrial.csv",
    "data/bnn/b_fc1.npy",
    "data/bnn/b_fc2.npy",
    "data/bnn/b_fc3.npy",
    "data/bnn/b_fc4.npy",
    "data/bnn/W_fc1.npy",
    "data/bnn/W_fc2.npy",
    "data/bnn/W_fc3.npy",
    "data/bnn/W_fc4.npy",
    "data/cnn/b_conv1.npy",
    "data/cnn/b_conv2.npy",
    "data/cnn/b_fc1.npy",
    "data/cnn/b_fc2.npy",
    "data/cnn/t10k-images-idx3-ubyte.gz",
    "data/cnn/t10k-labels-idx1-ubyte.gz",
    "data/cnn/W_conv1.npy",
    "data/cnn/W_conv2.npy",
    "data/cnn/W_fc1.npy",
    "data/cnn/W_fc2.npy",
    "secretsanta.py",
    "helloworld.py",
    "oneliners.py",
    "bnnmnist.py",
    "cnnmnist.py",
    "dsa.py",
    "aes.py",
    "np_aes.py",
    "np_bnnmnist.py",
    "np_cnnmnist.py",
    "lpsolver.py",
    "kmsurvival.py",
    "elgamal.py"
]

[[fetch]]
from = "./py/mpyc/mpyc"
to_folder = "./mpyc"
files = [
    "__main__.py",
    "fingroups.py",
    "thresha.py",
    "mpctools.py",
    "README.md",
    "gfpx.py",
    "runtime.py",
    "asyncoro.py",
    "numpy.py",
    "seclists.py",
    "sectypes.py",
    "random.py",
    "gmpy.py",
    "secgroups.py",
    "finfields.py",
    "statistics.py",
    "__init__.py"
]
